### ISSUE TITLE
Add quick "Add" buttons

### ISSUE THREAD

**Issue by mmillmor** [Charity-Connect/reading-charity-connect#11]
Users have reported confusion in creating offers and requests for help. Lets add some fast action buttons in a prominent place, e.g. top of the page or on a home page

1) Offer Help - opens a popup to create an offer to help
2) Request Help - opens a popup to pick a person who needs help and to add the details of what they need (i.e. a need request where you pick the person in the popup)

**Comment by RubiopRaul** [comment]
Completed
