### ISSUE TITLE
Incorrect user is shown when accessing a particular user via system admin tab

### ISSUE THREAD

**Issue by kiran-bahra** [Charity-Connect/reading-charity-connect#123]
Go to Admin -> organizations, then select an organization and select a user

It will open a new page where it tells you the information about the user, but the user it shows you is not the correct user - if you look in the URL you can see the id that the system looked up.

The system looked up the value stored under id in the table 'user_organizations' rather than looking up the value of user_id in that same table as it should have done. Therefore, an incorrect user, or in some cases no user, is shown.

**Comment by paisaksen** [comment]
When creating a user via the (system) "Admin" page, upon saving it gives
`error: "Name not set."`

In console it gives
`jquery-3.5.1.js:10099 POST http://localhost/rest/users 400 (Bad Request)`
`restClient.js:44 Error occured in REST client, when sending POST to url: /rest/users`
`user data not posted`

Nothing changes in the databases.
