### ISSUE TITLE
Creation of users from system admin throws error

### ISSUE THREAD

**Issue by rushil-ambati** [Charity-Connect/reading-charity-connect#125]

**Comment by paisaksen** [comment]
When creating a user via the (system) "Admin" page, upon saving it gives
`error: "Name not set."`

In console it gives
`jquery-3.5.1.js:10099 POST http://localhost/rest/users 400 (Bad Request)`
`restClient.js:44 Error occured in REST client, when sending POST to url: /rest/users`
`user data not posted`

Nothing changes in the databases.
