### ISSUE TITLE
Creation of users from organisation admin throws error

### ISSUE THREAD

**Issue by rushil-ambati** [Charity-Connect/reading-charity-connect#126]
undefined index user_id and different error for duplicate entry for key email_unique in User.php line 52

**Comment by rushil-ambati** [comment]
Error:
```
<br />
<b>Notice</b>:  Undefined index: user_id in <b>/home/rushil/Documents/PROJECTS/reading-charity-connect/rest/user_organizations.php</b> on line <b>51</b><br />
<br />
<b>Fatal error</b>:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_id' cannot be null in /home/rushil/Documents/PROJECTS/reading-charity-connect/entities/UserOrganization.php:44
Stack trace:
#0 /home/rushil/Documents/PROJECTS/reading-charity-connect/entities/UserOrganization.php(44): PDOStatement-&gt;execute(Array)
#1 /home/rushil/Documents/PROJECTS/reading-charity-connect/rest/user_organizations.php(52): UserOrganization-&gt;create()
#2 {main}
  thrown in <b>/home/rushil/Documents/PROJECTS/reading-charity-connect/entities/UserOrganization.php</b> on line <b>44</b><br />
```

**Comment by rushil-ambati** [comment]
User is created in backend, but front-end does not close pop-up dialog and does not reload table with a new GET request.
Refresh is required to show new user.

**Comment by rushil-ambati** [comment]
When duplicate email is found, and user selects to continue creation of user, system creates user with the same name as the duplicate found user, overriding the username that was set.
eg. if John Smith (js@email.com) exists, and I try to create Jonny Smith (js@email.com) and hit Yes to the duplicate pop-up, it will create a second entry of John Smith (js@email.com).

is that intended?

**Comment by mmillmor** [comment]
No, it's not intended. It should not allow you to create a user with the same e-mail. Instead it should add the existing user to your organization.

**Comment by rushil-ambati** [comment]
Have fixed the error, but the postText denoting successful save does not show

**Comment by rushil-ambati** [comment]
> No, it's not intended. It should not allow you to create a user with the same e-mail. Instead it should add the existing user to your organization.

@mmillmor If the user we're creating has the same email _within the same organisation_ (eg from the org admin panel), surely we just don't want to allow them to create a dupe user in the first place?

**Comment by mmillmor** [comment]
If it's the same e-mail in the same organization, yes, you are correct - prevent them from creating the new user.
