### ISSUE TITLE
Duplicate user creation exhibits unexpected behaviour

### ISSUE THREAD

**Issue by rushil-ambati** [Charity-Connect/reading-charity-connect#132]
When a user is created, if a user with the same email is found:
- If the user that is attempting to be created is in the same organisation as the duplicate found user, disallow any changes to the database: the user should **not** be created.
- If the user that is attempting to be created is in another organisation as the duplicate found user, simply create a new link in `user_organizations` between that currently existing user and the organisation that attempted to create it.

The current behaviour is as follows:
- When a duplicate user is found and they are in the same organisation as the newly created user, a pop-up shows asking if the user would still like to create a new user, and if Yes is selected, a duplicate link entry in `user_organizations` is created to the same user, with a different UID. If No is selected, the pop-up exits and so does the Save pop-up.
- When a duplicate user is found and they are in a different organisation from the newly created user, a pop-up shows asking if the user would still like to create a new user, and if Yes is selected, nothing seems to happen on UI and there is an error in the console as below, and the pop-up does not close and nothing happens to the database. If No is selected, it closes both pop-ups.

**Comment by mmillmor** [comment]
The behaviour should be if the user is in the current organisation, don't allow them to create. If they are in a different organisation, ask them if they want to add the use to the organisation. If Yes, just add them. If No, do nothing.

**Comment by mmillmor** [comment]
Similar to this, if you try to update a user's e-mail address to one that already exists, show an error saying "This e-mail address is already in use by a different user".

**Comment by kiran-bahra** [comment]
#143 fixes the problem for org admin tab, but we still need to do system admin tab
