### ISSUE TITLE
Add created date/update date etc

### ISSUE THREAD

**Issue by mmillmor** [Charity-Connect/reading-charity-connect#5]
Add created date, created by (user_id), last_update_date and last_updated_by (user_id) to all records.

**Comment by mmillmor** [comment]
Added the writing of the data to the tables. Now need to expose it through the rest services, and then potentially through the UI (need to decide on the UI).

**Comment by RubiopRaul** [comment]
Added creation_date, created_by, update_date and updated_by to rest web services. Still need to work on UI.

**Comment by mmillmor** [comment]
For the UI, on the client and the offer, lets put 2 read only fields at the bottom of the details showing updated by (which should be a user e-mail address), and update date, in local format. Ideally less obtrusive than the regular fields - perhaps smaller, with a prompt to the left, not above, e.g.
Last updated at 12:31 13/6/2020 by martin@example.com

**Comment by RubiopRaul** [comment]
> For the UI, on the client and the offer, lets put 2 read only fields at the bottom of the details showing updated by (which should be a user e-mail address), and update date, in local format. Ideally less obtrusive than the regular fields - perhaps smaller, with a prompt to the left, not above, e.g.
> Last updated at 12:31 13/6/2020 by [martin@example.com](mailto:martin@example.com)

Done in last pull. Please tell if anything is missing before closing this issue.

**Comment by RubiopRaul** [comment]
Completed
