### ISSUE TITLE
Erroneous display fields on client creation

### ISSUE THREAD

**Issue by rushil-ambati** [Charity-Connect/reading-charity-connect#56]
When a client is initially created with the "Add Client" button, the needs tab below the client's details has the header "undefined's needs". This should be hidden until the client is given a name.

Also, the needs list remains stuck on "Initialising" when there are no needs. There should be a special case for retrieval of needs on creation to just show "No needs data." when a client is first created.

**Comment by mmillmor** [comment]
Done
