### ISSUE TITLE
Dynamic buttons on requests screen

### ISSUE THREAD

**Issue by mmillmor** [Charity-Connect/reading-charity-connect#9]
On the requests screen, the action buttons should depend on the current state of the request.

If the request is unaccepted, buttons are Agree To Help and Unable To Help. 
If the request is accepted, buttons are "Mark as Done" and "Cancel Offer To Help". 
If the request is Rejected, buttons are "Agree To Help". 
If the request is Complete, buttons are "Mark as Incomplete" 

The actions are;

Mark as Done -> agreed=Y,complete=Y
Cancel Offer To Help -> agreed=N, complete=N
Agree To Help -> agreed=Y, complete=N
Mark as Incomplete - > agreed=Y, Complete=N

Clicking on the buttons should perform the action immediately. No Save is required.

**Comment by OliHarris** [comment]
NOTE: "Unable To Help" and "Cancel Offer To Help" I've combined into the latter.
First part is done - removing the Save button can come next...

**Comment by mmillmor** [comment]
Thanks Oli. With  "Unable To Help" and "Cancel Offer To Help" - you can't cancel an offer you have never made. They may have the same technical action, but to the user it means different things. We need different buttons or different button labels, depending on the state - i.e. if agreed is null, it is Unable To Help. If agreed is Y, it is Cancel Offer To Help

**Comment by OliHarris** [comment]
Yea I was a bit confused last night - good to clarify.
It's because your list for "The actions are highlighted the four use cases - "Unable To Help"; I wasn't sure what to do with.
I can add this button; when clicked same function as "Cancel Offer To Help"?

**Comment by OliHarris** [comment]
Updated 'decisionCancel' label on #unacceptedOptions to caption "Unable To Help"

**Comment by OliHarris** [comment]
"Clicking on the buttons should perform the action immediately. No Save is required" - DONE!

**Comment by OliHarris** [comment]
OK that's gone in 'develop' branch

**Comment by OliHarris** [comment]
Code merged - will close ticket :)
